const dumbSearch = require('./dumbSearch');
const binarySearch = require('./binarySearch');
const selectionSort = require('./selectionSort');
const sum = require('./sum');
const recursiveSum = require('./recursiveSum');
const recursiveCount = require('./recursiveCount');
const max = require('./max');
const recursiveMax = require('./recursiveMax');
const recursiveBinarySearch = require('./recursiveBinarySearch');
const quickSort = require('./quickSort');

// dumbSearch();
// binarySearch();
// selectionSort();
// sum();
// recursiveSum();
// recursiveCount();
// max();
// recursiveMax();
// recursiveBinarySearch();
quickSort();
