// algorithms
const dumbSearch = require('./functions/dumbSearch');
const binarySearch = require('./functions/binarySearch');
const selectionSort = require('./functions/selectionSort');
const sum = require('./functions/sum');
const recursiveSum = require('./functions/recursiveSum');
const recursiveCount = require('./functions/recursiveCount');
const max = require('./functions/max');
const recursiveMax = require('./functions/recursiveMax');
const recursiveBinarySearch = require('./functions/recursiveBinarySearch');
const { run: quickSort } = require('./functions/quickSort');
const breadthFirstSearch = require('./functions/breadthFirstSearch');
const dijkstrasSearch = require('./functions/dijkstrasSearch');
// tasks
const rocksAndTreasures = require('./tasks/rocksAndTreasures');
const anagrams = require('./tasks/anagrams');
const generationBracketSequences = require('./tasks/generationBracketSequences');
const mergingLists = require('./tasks/mergingLists');
const sockMerchant = require('./tasks/sockMerchant');
const countingValleys = require('./tasks/countingValleys');
const jumpingOnTheClouds = require('./tasks/jumpingOnTheClouds');
const repeatedString = require('./tasks/repeatedString');
const palindrome = require('./tasks/palindrome');
const compressionIntegerArray = require('./tasks/compressionIntegerArray');
const centuryFromYear = require('./tasks/centuryFromYear');
const parenthesisSequence = require('./tasks/parenthesisSequence');

// dumbSearch();
// binarySearch();
// selectionSort();
// sum();
// recursiveSum();
// recursiveCount();
// max();
// recursiveMax();
// recursiveBinarySearch();
// quickSort();
// breadthFirstSearch();
// dijkstrasSearch();

// rocksAndTreasures();
// anagrams();
// generationBracketSequences();
// mergingLists();
// sockMerchant();
// countingValleys();
// jumpingOnTheClouds();
// repeatedString();
// palindrome();
// compressionIntegerArray();
// centuryFromYear();
parenthesisSequence();
