const dumbSearch = require('./functions/dumbSearch');
const binarySearch = require('./functions/binarySearch');
const selectionSort = require('./functions/selectionSort');
const sum = require('./functions/sum');
const recursiveSum = require('./functions/recursiveSum');
const recursiveCount = require('./functions/recursiveCount');
const max = require('./functions/max');
const recursiveMax = require('./functions/recursiveMax');
const recursiveBinarySearch = require('./functions/recursiveBinarySearch');
const quickSort = require('./functions/quickSort');
const breadthFirstSearch = require('./functions/breadthFirstSearch');
const dijkstrasSearch = require('./functions/dijkstrasSearch');

// dumbSearch();
// binarySearch();
// selectionSort();
// sum();
// recursiveSum();
// recursiveCount();
// max();
// recursiveMax();
// recursiveBinarySearch();
// quickSort();
// breadthFirstSearch();
dijkstrasSearch();
